models:
  - name: rudder_user_id_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      main_id_type: main_id
      edge_sources:
      # Specify from inputs.yaml file
        - inputs/rsIdentifies
        - inputs/rsTracks
        - inputs/rsPages
        - inputs/rsProductAdded
        - inputs/rsOrderCompleted
        - inputs/rsCheckoutStepCompleted
 
  - name: rudder_user_ecommerce_features
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day      
      entity_key: user
      vars:
        #last_transaction_value
        - entityvar:
            name: last_transaction_value
            from: inputs/rsOrderCompleted
            select: first_value(PROPERTIES_REVENUE)
            window:
              order_by: 
              - case when PROPERTIES_REVENUE is not null then 2 else 1 end desc
              - timestamp desc
        #avg_transaction_value
        - entityvar:
            name: avg_transaction_value
            select: avg( PROPERTIES_REVENUE ::real)
            from: inputs/rsOrderCompleted
        #avg_units_per_transaction
        - entityvar:
            name: avg_units_per_transaction
            select: avg(array_size (parse_json( PROPERTIES_PRODUCTS) )::real)
            from: inputs/rsOrderCompleted
        #highest_transaction_value
        - entityvar:
            name: highest_transaction_value
            select: max(PROPERTIES_REVENUE ::real)
            from: inputs/rsOrderCompleted
        #median_transaction_value
        - entityvar:
            name: median_transaction_value
            select: median( PROPERTIES_REVENUE ::real)
            from: inputs/rsOrderCompleted
        #transactions_in_past_90_days
        - entityvar:
            name: transactions_in_past_90_days
            select: count(*)::real
            from: inputs/rsOrderCompleted
            where: datediff(day,date(timestamp),date('{{timestamp.Format("2006-01-02 15:04:05")}}'))<=90

        #days_since_last_purchase
        
        - entityvar:
            name: max_timestamp_order_created
            select: max(timestamp)
            from: inputs/rsOrderCompleted
        
        - entityvar:
            name: days_since_last_purchase
            select: datediff(day, date(max_timestamp_order_created), date('{{timestamp.Format("2006-01-02 15:04:05")}}'))
        #total_transactions
        - entityvar:
            name: total_transactions
            select: count(*)
            from: inputs/rsOrderCompleted
        #has credit card
        - entityvar:
            name: has_credit_card
            select: max(case when lower(PROPERTIES_PAYMENT_METHOD) in ('visa','american express','mastercard') then 1 else 0 end)
            from: inputs/rsCheckoutStepCompleted 
        #days since first purchase

        - entityvar:
            name: min_timestamp_order_created
            select: min(timestamp)
            from: inputs/rsOrderCompleted

        - entityvar:
            name: days_since_first_purchase
            select: datediff(day, date(min_timestamp_order_created), date('{{timestamp.Format("2006-01-02 15:04:05")}}'))
        
        #gross_amt_spent_in_past
        - entityvar:
            name: gross_amt_spent_in_past
            select: sum(PROPERTIES_REVENUE::real)
            from: inputs/rsOrderCompleted
        #items_purchased_ever
        - entityvar:
            name: items_purchased_ever
            select: array_agg(PROPERTIES_SKU)
            from: inputs/rsProductAdded
        #carts_in_past_365_days
        - entityvar:
            name: carts_in_past_365_days
            select: count(distinct PROPERTIES_CART_ID)
            from: inputs/rsProductAdded
            where:  datediff(day,date(timestamp),date('{{timestamp.Format("2006-01-02 15:04:05")}}')) <= 365 

        #total_carts
        - entityvar:
            name: total_carts
            select: count(distinct PROPERTIES_CART_ID)
            from: inputs/rsProductAdded
        #products_added_in_past_365_days
        - entityvar:
            name: products_added_in_past_365_days
            select: array_agg(distinct PROPERTIES_PRODUCT_ID)
            from: inputs/rsProductAdded
            where: datediff(day, date(timestamp), date('{{timestamp.Format("2006-01-02 15:04:05")}}')) <= 365
    
        #total_products_added
        - entityvar:
            name: total_products_added
            select: array_agg(distinct PROPERTIES_PRODUCT_ID)
            from: inputs/rsProductAdded
        #max_timestamp_product_added
        - entityvar:
            name: max_timestamp_product_added
            select: max(timestamp)
            from: inputs/rsProductAdded
      
        #days_since_last_cart_add
        - entityvar:
            name: days_since_last_cart_add
            select: datediff(day, date(max_timestamp_product_added), date('{{timestamp.Format("2006-01-02 15:04:05")}}'))
       
      
      features:
        - last_transaction_value
        - avg_transaction_value
        - avg_units_per_transaction
        - highest_transaction_value
        - median_transaction_value
        - transactions_in_past_90_days
        - days_since_last_purchase
        - total_transactions
        - has_credit_card
        - days_since_first_purchase
        - gross_amt_spent_in_past
        - items_purchased_ever
        - days_since_last_cart_add
        - total_products_added
        - carts_in_past_365_days
        - total_carts